# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-alpine3.21

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: go build -C ./src/netcalc -o /netcalc -v

    - name: Test
      run: go test -C ./src/netcalc -v

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: save artifact
        path: ./netcalc
